"""Auto Vote

Revision ID: 4610c7719fd7
Revises: bf0618a8a795
Create Date: 2024-01-24 12:57:46.466884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4610c7719fd7'
down_revision: Union[str, None] = 'bf0618a8a795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('products',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    # sa.Column('is_sale', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    # sa.Column('inventory', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIME(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='products_pkey')
    # )
    op.drop_table('votes')
    # ### end Alembic commands ###
