"""Add Phone No.

Revision ID: aefb02ad602f
Revises: 4610c7719fd7
Create Date: 2024-01-24 13:43:21.867565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefb02ad602f'
down_revision: Union[str, None] = '4610c7719fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_no')
    # ### end Alembic commands ###
